# do not install anything extra onto the image
language: Objective-C

# use a Mac OSX image
os: osx

# only run builds on pushes to the master branch
branches:
  only:
  - master

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change

# decrypt the encrypted SSH key file so it can be used for scp auth in post_build.sh
before_install:
- openssl aes-256-cbc -k "Support123" -in "${UPLOAD_KEYPATH}.enc" -out "${UPLOAD_KEYPATH}" -d

# run the script to download and install Unity editor
install:
- sudo -E sh ./Scripts/install.sh

# run the script for unit tests and builds
script:
- sudo -E sh ./Scripts/build.sh

# run the script to upload the builds as tarballs
after_success:
- sudo -E sh ./Scripts/post_build.sh

# environment variables used in bash scripts
env:
  global:
  - UNITYCI_PROJECT_NAME="Zürich3D"
  - UPLOAD_KEYPATH="./Scripts/upload"
  - secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQDGB2s3IWo6JR4rtDuceSkM/oe92VT2nhMvSp50O9MRP7pUbQosjxfWidfGtXUnncsG9OyRFTDFuZb8zLIWeaNG+UbJ1y/ONrQu5K7UTgwPgcKqb4A1mSiaY0b21dMG84r+3I3rScr6BP6R3WTRFGqGY638lrG77FMkJYeIZcuR8FgYM28J7wI+2o07cLL0vQsxPS2jXt7y/dSvv6VJ4esv2kSyaeXtKhIVCvoENoeDF8C/iJKvq15aORPOu7ymvVOl+WuhvUBEY8l/ZYfCY8Ukcy1fP7MHlowsy/1Di8ySR1+Sp/neYO01pqg+tANBPq2DrVn850lzstfRiJK6fzVrroVje2plc1rb0xtp5Ut82sJyjuFtKg0uHdh88QDHqDBGtNSY5EAzeVVsMRQgWToJ/GQlLwelDIqFnxeWfoT2VA8aR+EtTCn1HGMh4nr+QhvMpi9OpA83VmOU5oMfX4E015I/uC3bZcU1eVVkEKJARUSfX5BsrhcmUrIKDNQNSRHYKUZHfBWn6ui1afO31ydHPQXf8isLV/mfVv31XCp8GAA2AZHC1HVV9f+AVSg2FfX0qCuDtUTqcXmUF+GYL0hYCaUGZvPv3QkYyoPTLlK3bpvl+YQS7lY6c9tnQcCNj5HsH258IH36givVqqPOanItD1Y4Enn50YZKBPDD4bClLQ== zuerich3d.org@protonmail.com
